config {
  type: "view",
  schema: "warehouse_staging",
  assertions: {
    uniqueKey: ["order_item_id"],
    nonNull: [
      "order_item_id",
      "order_id",
      "product_id",
      "quantity",
      "unit_price"
    ]
  }
}

SELECT
  CAST(order_item_id AS INT64) AS order_item_id,
  CAST(order_id AS INT64) AS order_id,
  CAST(product_id AS INT64) AS product_id,
  CAST(quantity AS INT64) AS quantity,
  CAST(unit_price AS NUMERIC) AS unit_price
FROM ${ref("public_order_items")}